dependencies:
  # - <organization/repo>@<version>. Check github at https://github.com/smartcontractkit/chainlink-brownie-contracts
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

dotenv: .env

# Any network cn have its only price feeds and adressess.
networks:
  default: solidity-learn # No need to include: --network solidity learn
  kovan:
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  solidity-learn:
    verify: False

wallets:
  from_key: ${PRIVATE_KEY}
